### ISSUE TITLE
User couldn't register if checked Volunteer questionnaire checkbox

### ISSUE THREAD

**Issue by BirenRathod** [BiologicalRecordsCentre/volunteer-questionnaires#1]
@johnvanbreda I can't able to register if I checked the checkbox of Volunteer questionnaire checkbox on NPMS.

Here is the log from NPMS website -> https://www.npms.org.uk/admin/reports/dblog/event/16

The NPMS is the first to start with but other website will be using it soon.

**Comment by johnvanbreda** [comment]
I have an existing account with username johnvanbreda but don't have access to the logs.

**Comment by BirenRathod** [comment]
@johnvanbreda I have made an admin now.

**Comment by BirenRathod** [comment]
Also, you can produce same error by editing same checkbox from your own profile too.

**Comment by BirenRathod** [comment]
@johnvanbreda did you get a chance to look into this issue?

**Comment by johnvanbreda** [comment]
Have committed a fix for you to try.

**Comment by BirenRathod** [comment]
Thanks, @johnvanbreda. I will let you know soon if any problem.

**Comment by BirenRathod** [comment]
Thanks @johnvanbreda. That works.
